list_user:
    path:       /api/users/{id}
    controller: App\Controller\UsersController::list
    methods:    GET
list_all_users:
    path:       /api/users
    controller: App\Controller\UsersController::all
    methods:    GET
register_user:
    path:       /register/{username}/{password}
    controller: App\Controller\UsersController::registerUser
    methods:    POST
delete_user:
    path:       /api/users/delete/{id}
    controller: App\Controller\UsersController::deleteUser
    methods:    POST
logout:
    path:       /logout
    controller: App\Controller\UsersController::logout
    methods:    POST
update_username:
    path:       /api/users/update/username/{username}/{newUsername}
    controller: App\Controller\UsersController::updateUsername
    methods:    POST
update_password:
    path:       /api/users/update/password/{username}/{password}/{newPassword}
    controller: App\Controller\UsersController::updatePassword
    methods:    POST
login:
    path:       /login/{username}/{password}
    controller: App\Controller\UsersController::loginUser
    methods:    POST