<?php

namespace ContainerIenyd63;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wpzi2e5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wpzi2e5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wpzi2e5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', true],
        ], [
            'encoder' => '?',
            'validator' => '?',
        ]);
    }
}
