<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmjNon2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmjNon2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZmjNon2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZmjNon2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZmjNon2\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZmjNon2',
    'container.build_id' => 'e0cc8b4f',
    'container.build_time' => 1624356315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmjNon2');
