<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRuSxYwu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRuSxYwu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRuSxYwu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRuSxYwu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRuSxYwu\App_KernelDevDebugContainer([
    'container.build_hash' => 'RuSxYwu',
    'container.build_id' => '36bba7e2',
    'container.build_time' => 1624271235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRuSxYwu');
