<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'register_user' => [['username', 'password'], ['_controller' => 'App\\Controller\\AuthController::registerUser'], [], [['variable', '/', '[^/]++', 'password', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/register']], [], []],
    'login_user' => [['username', 'password'], ['_controller' => 'App\\Controller\\AuthController::loginUser'], [], [['variable', '/', '[^/]++', 'password', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/login']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\AuthController::logout'], [], [['text', '/logout']], [], []],
    'show_user' => [['id'], ['_controller' => 'App\\Controller\\UsersController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users/show']], [], []],
    'list_all_users' => [[], ['_controller' => 'App\\Controller\\UsersController::list'], [], [['text', '/api/users/list']], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\UsersController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users/delete']], [], []],
    'update_username' => [['username', 'passwordNew'], ['_controller' => 'App\\Controller\\UsersController::updatePassword'], [], [['variable', '/', '[^/]++', 'passwordNew', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/api/users/update/password']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
