<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'list_user' => [['id'], ['_controller' => 'App\\Controller\\UsersController::list'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], []],
    'list_all_users' => [[], ['_controller' => 'App\\Controller\\UsersController::all'], [], [['text', '/api/users']], [], []],
    'register_user' => [['username', 'password'], ['_controller' => 'App\\Controller\\UsersController::registerUser'], [], [['variable', '/', '[^/]++', 'password', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/register']], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\UsersController::deleteUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users/delete']], [], []],
    'logout_user' => [[], [], [], [['text', '/api/logout']], [], []],
    'update_username' => [['username', 'newUsername'], ['_controller' => 'App\\Controller\\UsersController::updateUsername'], [], [['variable', '/', '[^/]++', 'newUsername', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/api/users/update/username']], [], []],
    'update_password' => [['username', 'password', 'newPassword'], ['_controller' => 'App\\Controller\\UsersController::updatePassword'], [], [['variable', '/', '[^/]++', 'newPassword', true], ['variable', '/', '[^/]++', 'password', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/api/users/update/password']], [], []],
    'login' => [['username', 'password'], ['_controller' => 'App\\Controller\\UsersController::loginUser'], [], [['variable', '/', '[^/]++', 'password', true], ['variable', '/', '[^/]++', 'username', true], ['text', '/login']], [], []],
];
